spring.application.name=queuecart

spring.datasource.url=jdbc:postgresql://localhost:5432/queuecart_db
spring.datasource.username=postgres
spring.datasource.password=senhor_cafe101
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=cLeIC85/gE1yp+ugJ6BenFhbz6YBlcPiO6tOXLDfWvwFao7ap8P7b9KvLCFyBtZJ
jwt.expiration-ms=3600000